### ISSUE TITLE
L Nav contracts (shows only top level navs) when I click an article in the L Nav (whereas prior to this the L nav remained expanded on the newly opened article display)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#54] opened 2019-11-16 01:26 UTC
Update: During the time of writing this issue report, the behavior has already switched back, it appears (to showing the L nav expanded). Not sure why this change back and forth happened.

**Describe the bug**
L Nav contracts (shows only top level navs) when I click an article in the L Nav (whereas prior to this the L nav remained expanded on the newly opened article display)

This is how the Site displayed a few minutes ago (showing the L nav expanded still, when I arrive on a new article).
![image](https://user-images.githubusercontent.com/51930500/68985500-c26e8580-07cb-11ea-8326-d5991726b7bd.png)

This is how the Site displays now (at time of writing this issue report, showing only the top level navs).
![image](https://user-images.githubusercontent.com/51930500/68985491-a9fe6b00-07cb-11ea-8c07-d5d6816261c9.png)

Not sure which way is better (expanded or contracted) after clicking a link in the L nav (and reaching that newly opened page). But I thought there was some benefit to having the L nav expanded (open), likely because I'm clicking through the articles one at a time right now, so having them open is helpful.

If possible, perhaps a helpful behavior would be that the L nav remains displayed (on the newly opened page) as it was (on the page with the clicked link) - ie. if the L nav was expanded, then it stays expanded. If it was contracted (top navs displayed only), then it remains contracted.

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/marketing/automating-store-emails-by-using-notification-templates.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/marketing/automating-store-emails-by-using-notification-templates.html

**Comment by rdai10** [comment] 2019-11-16 01:39
Hey @andrewwilkinsonLR,

This inconsistency may be due to the fact that we recently redeployed the site. Can you double check to see if you can reproduce this behavior?

**Comment by andrewwilkinsonLR** [comment] 2019-11-16 01:46
The behavior I see now is that the L nav is expanded on the new page after I click an article link in the L nav.

If it's possible (& not too difficult) perhaps the L nav could open/display to the location in the L nav where the newly opened article is in the L nav.

For example, when I click an article in the L Nav (Adding Regions, in this case), the left nav on the newly opened page is expanded _and_ at the top of the nav.
![image](https://user-images.githubusercontent.com/51930500/68985965-905f2280-07cf-11ea-91a7-d085eb52f660.png)

Alternatively, perhaps the L nav could display like this on the newly opened page (showing the currently displayed article in the left nav automatically upon opening the page).
![image](https://user-images.githubusercontent.com/51930500/68985981-bc7aa380-07cf-11ea-9ffb-9db09c9e9aee.png)

**Comment by andrewwilkinsonLR** [comment] 2019-11-19 20:18
@jrhoun and @rdai10 , here's the behavior I see today on learn.liferay.com:

USER GUIDE
 * Click "User Guide" -> goes to almost blank page (in terms of content below the ribbon and R of the L nav), and the L nav is expanded below "User Guide"
![image](https://user-images.githubusercontent.com/51930500/69181852-bc76ee00-0ac4-11ea-8290-d4daaf36e20f.png)

 * Click an article in the user guide BELOW the visible top-most L nav articles, and then on that article, that article is STILL not visible in the L nav because the L nav goes back to the top.
![image](https://user-images.githubusercontent.com/51930500/69181964-f6e08b00-0ac4-11ea-9525-709212634d14.png)

 * A) If I click "User Guide" in the L nav, I see this, again:
![image](https://user-images.githubusercontent.com/51930500/69182087-2becdd80-0ac5-11ea-8a1f-268a02b68c7e.png)

 * B) But if I click "Go Back" in the L nav, I see this User Guide sub-outline for "Getting Started" (getting-started/index.html) page, **which the only other way I see to navigate to this is via the breadcrumbs, which is also in hindsight, ie. _after_ I navigate to an article**.
![image](https://user-images.githubusercontent.com/51930500/69182062-1f688500-0ac5-11ea-9fce-b5b3bd006c99.png)

 * B-2) And if from "B" above, I click "Go Back" in the L nav, again, I see this User Guide main-outline (index.html) page, **which, again, the only other way I see to navigate to this is via the breadcrumbs, which is also in hindsight, ie. _after_ I navigate to an article**.
![image](https://user-images.githubusercontent.com/51930500/69182338-a9185280-0ac5-11ea-9eb0-af50175fb91d.png)

In other words, there is no visible hierarchy _before_ I click on an article in the L nav - it appears 'flat'. Then after I click an article, I can see some depth (not as flat) via the breadcrumbs and find how the articles are grouped/organized.

And I'd still thinks it's worth considering having the L nav stay where the clicked article is (vs go back to the top).

DEV GUIDE
 * Click "Developer Guide" -> goes to almost blank page (in terms of content below the ribbon and R of the L nav), and the L nav is expanded below "User Guide"
![image](https://user-images.githubusercontent.com/51930500/69182695-61de9180-0ac6-11ea-87a8-eb357222a031.png)

 * Click an article in the dev guide BELOW the visible top-most L nav articles, and then on that article, that article is STILL not visible in the L nav because the L nav goes back to the top.
![image](https://user-images.githubusercontent.com/51930500/69182721-6f941700-0ac6-11ea-85ea-398d529439ca.png)

 * A) If I click "Developer Guide" in the L nav, I see this, again:
![image](https://user-images.githubusercontent.com/51930500/69182755-82a6e700-0ac6-11ea-86fe-48a472c8d6cf.png)

 * B) But if I click "Go Back" in the L nav, I see this Developer Guide main-outline (there are no sub-outlines) (index.html) page, **which the only other way I see to navigate to this is via the breadcrumbs, which is also in hindsight, ie. _after_ I navigate to an article**.
![image](https://user-images.githubusercontent.com/51930500/69182803-9ce0c500-0ac6-11ea-866e-85b104f29337.png)

So, the L Nav and navigating/clicking experience is similar for both user guide and dev guide.

**Comment by jrhoun** [comment] 2019-11-19 21:36
Got it. The above issue you're identifying we have a fix that we're testing right now. Will update this issue once we test it out more.

**Comment by jrhoun** [comment] 2019-11-20 17:53
Hi @andrewwilkinsonLR this issue should mostly be fixed - going to close this. Please reopen if you encounter navigation weirdness on the site.

**Closed by jrhoun** 2019-11-20 17:53 UTC
