### ISSUE TITLE
Right nav bolding/blue is 'sticky' (doesn't always show the selected/clicked section)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#47] opened 2019-11-15 23:04 UTC
**Describe the bug**
Right nav bolding/blue is 'sticky' (doesn't always show the selected/clicked section). And sometimes the "Additional Information" R nav never bolds/blues.

Example: On this page (Sites and Site Types), I refresh the page (fresh start), click the R nav "Additional Information" (and it doesn't bold/blue); instead "Setting a Site Type" bolds/blues. Then, I click "Site Types" (and it doesn't bold/blue); instead, again, "Setting a Site Type" bolds/blues. (I think this has to do with where the screen is, or what is viewable on the screen, not sure.) The screenshot below represents after this step.

Not a major deal, but seems clunky, off, weird to click a nav, and it not go bold, while another section title is/remains bold instead.

![image](https://user-images.githubusercontent.com/51930500/68981530-939ae400-07b8-11ea-875e-955b678805c3.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/getting-started/sites-and-site-types.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/html/user-guide/getting-started/sites-and-site-types.html#site-types

**Comment by jrhoun** [comment] 2019-11-21 17:46
Closing this issue as a duplicate of #21

**Closed by jrhoun** 2019-11-21 17:46 UTC
Labels: site bug
