### ISSUE TITLE
Email address (with no additional formatting other than italics) does not format as clickable link (ie. mailto: email address)

### ISSUE THREAD

**Issue by andrewwilkinsonLR** [liferay/liferay-learn#53] opened 2019-11-16 01:09 UTC
**Describe the bug**
Email address (with no additional formatting other than italics) does not format as clickable link (ie. mailto: email address)

The markdown on this page has the following text: "for example: _orders@yourstore.com_". Github formats the email address as a clickable link (which is what I think I'm used to on other sites, and seems like a good idea to me). The site shows the italics, but it is not a clickable link.

![image](https://user-images.githubusercontent.com/51930500/68985199-ad90f280-07c9-11ea-975e-062fde17a016.png)

Github: https://github.com/jrhoun/liferay-learn/blob/master/docs/commerce/2.x/en/user-guide/marketing/automating-store-emails-by-using-notification-templates.md

Site: https://s3.wasabisys.com/learn.liferay.com/commerce-2.x/user-guide/marketing/automating-store-emails-by-using-notification-templates.html

**Comment by rdai10** [comment] 2019-11-16 01:42
Hey @andrewwilkinsonLR 
This is the expected behaviour as the markup in the markdown indicates it should be displayed as italicized. Perhaps try following the markup indicated on https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses?

**Comment by andrewwilkinsonLR** [comment] 2019-11-16 01:49
@rdai10, sure - that solution (using the < > per the markdown guide) makes sense. @jrhoun, does Rdai10's solution sound good to you (ie. write the markdown differently)?

**Comment by jrhoun** [comment] 2019-11-16 02:03
Hey @andrewwilkinsonLR - in the cases where we actually _want_ someone to click on an email address - lets say hypothetically to send an email to Liferay Support or something like that - then we **should** adopt the syntax. But in this specific example, I wouldn't consider this an issue because it is an example email - written for example purposes, not to be clicked by someone because the email won't actually go anywhere, making it an actual clickable email link is actually a worse UX because you're indicating that something is a link that is not intended to be. For that reason, closing this for now. Please let me know if you think we should make it clickable and your rationale. Thanks!

**Closed by jrhoun** 2019-11-16 02:03 UTC
Labels: documentation

**Comment by andrewwilkinsonLR** [comment] 2019-11-16 02:09
@jrhoun, agreed. Are you aware of any emails in the documentation where we do want the link/clickability (such as emailing Support)? Or aware whether there's an easy way for someone to search for those email addresses, so that the < > can be added to them (if missing) such that the email addresses format as a link in those cases?

**Comment by jrhoun** [comment] 2019-11-16 18:16
@andrewwilkinsonLR - nothing jumps out at me right away, and I am also not aware of a quick way to search for those instances that may exist.

**Comment by rdai10** [comment] 2019-11-17 06:24
Hey @jrhoun @andrewwilkinsonLR: I looked, there were only 2 instances of references to emails. Both are example emails.
